/**
 * Trading Types for AutoPilot System
 * Internal trade intentions, positions, risk management
 */

export type TradeDirection = 'BUY' | 'SELL';
export type PositionStatus = 'OPEN' | 'CLOSED' | 'PARTIALLY_CLOSED';
export type RiskGrade = 'LOW' | 'MEDIUM' | 'HIGH';
export type TradeHorizon = 'INTRADAY' | 'SWING' | 'POSITIONAL';

/**
 * Trade Intention (INTERNAL ONLY - NOT EXPOSED TO USERS)
 * Generated by daily brain pipeline
 */
export interface TradeIntention {
  id?: string;
  date: string; // YYYY-MM-DD
  canonical_symbol: string;
  direction: TradeDirection;
  entry_zone_low: number;
  entry_zone_high: number;
  sl: number; // Stop loss
  tp1: number; // Take profit 1
  tp2: number; // Take profit 2 (optional)
  confidence: number; // 0-1 score from AI model
  risk_grade: RiskGrade;
  horizon: TradeHorizon;
  tags: string[]; // High-level only: "trend aligned", "volatility favorable"
  created_at?: string;
  expires_at?: string; // Intention expires if not executed
}

/**
 * Position (User's Active Trade)
 */
export interface Position {
  id?: string;
  user_id: string;
  canonical_symbol: string;
  broker_type: string;
  side: 'LONG' | 'SHORT';
  quantity: number;
  avg_entry_price: number;
  current_price?: number;
  unrealized_pnl?: number;
  unrealized_pnl_percent?: number;
  sl: number;
  tp1: number;
  tp2?: number;
  trailing_stop_enabled: boolean;
  trailing_stop_data?: {
    initial_sl: number;
    current_sl: number;
    trail_points: number;
    highest_price?: number;
  };
  status: PositionStatus;
  risk_snapshot: {
    risk_amount: number; // Rupees at risk
    risk_percent: number; // % of capital
    position_size_method: string;
  };
  trade_intention_id?: string; // Link to original intention
  entry_timestamp: string;
  exit_timestamp?: string;
  created_at?: string;
  updated_at?: string;
}

/**
 * Order (Execution Record)
 */
export interface Order {
  id?: string;
  user_id: string;
  broker_type: string;
  broker_order_id?: string;
  canonical_symbol: string;
  side: TradeDirection;
  quantity: number;
  order_type: 'MARKET' | 'LIMIT' | 'SL' | 'SL-M';
  price?: number;
  trigger_price?: number;
  status: 'PENDING' | 'OPEN' | 'FILLED' | 'PARTIALLY_FILLED' | 'CANCELLED' | 'REJECTED';
  filled_quantity?: number;
  average_fill_price?: number;
  slippage?: number; // Actual fill vs intended price
  rejection_reason?: string;
  position_id?: string; // Link to position
  trade_intention_id?: string; // Link to intention
  is_paper_trade: boolean;
  placed_at?: string;
  filled_at?: string;
  created_at?: string;
  updated_at?: string;
}

/**
 * Fill (Execution Detail)
 */
export interface Fill {
  id?: string;
  order_id: string;
  fill_price: number;
  fill_quantity: number;
  fill_timestamp: string;
  created_at?: string;
}

/**
 * Risk Limits (Per User)
 */
export interface RiskLimits {
  user_id: string;
  max_positions: number; // Max open positions at once
  max_daily_loss: number; // Max loss per day (rupees)
  max_daily_loss_percent: number; // Max loss per day (%)
  max_exposure: number; // Max total exposure (rupees)
  max_exposure_percent: number; // Max % of capital deployed
  risk_per_trade_percent: number; // Position sizing (% of capital per trade)
  created_at?: string;
  updated_at?: string;
}

/**
 * Performance Tracking (Daily Aggregation)
 */
export interface PerformanceDaily {
  user_id: string;
  date: string; // YYYY-MM-DD
  trades_count: number;
  wins: number;
  losses: number;
  win_rate: number; // 0-1
  avg_r: number; // Average R-multiple
  gross_pnl: number;
  net_pnl: number;
  fees: number;
  drawdown: number; // Max intraday drawdown
  created_at?: string;
}

/**
 * AutoPilot Status
 */
export type AutoPilotStatus = 'ON' | 'PAUSED' | 'PROTECT';

export interface AutoPilotState {
  user_id: string;
  status: AutoPilotStatus;
  is_paper_trading: boolean;
  capital_allocated: number;
  current_exposure: number;
  daily_pnl: number;
  daily_loss_remaining: number;
  positions_count: number;
  last_action_at?: string;
  updated_at?: string;
}

/**
 * Notification
 */
export type NotificationType =
  | 'ORDER_PLACED'
  | 'ORDER_FILLED'
  | 'ORDER_REJECTED'
  | 'POSITION_OPENED'
  | 'POSITION_CLOSED'
  | 'RISK_LIMIT_BREACH'
  | 'KILL_SWITCH_ACTIVATED'
  | 'BROKER_CONNECTION_ERROR'
  | 'AUTOPILOT_PAUSED';

export interface Notification {
  id?: string;
  user_id: string;
  type: NotificationType;
  title: string;
  message: string;
  severity: 'INFO' | 'WARNING' | 'ERROR';
  read: boolean;
  action_url?: string;
  created_at?: string;
}

/**
 * Audit Log
 */
export type AuditAction =
  | 'AUTOPILOT_ENABLED'
  | 'AUTOPILOT_DISABLED'
  | 'ORDER_PLACED'
  | 'ORDER_CANCELLED'
  | 'POSITION_CLOSED'
  | 'RISK_LIMIT_UPDATED'
  | 'KILL_SWITCH_ACTIVATED'
  | 'BROKER_CONNECTED'
  | 'BROKER_DISCONNECTED';

export interface AuditLog {
  id?: string;
  user_id?: string;
  action: AuditAction;
  payload: Record<string, any>;
  ip_address?: string;
  user_agent?: string;
  created_at?: string;
}

/**
 * Pipeline Run
 */
export type PipelineType = 'daily_brain' | 'executor' | 'position_monitor';
export type PipelineStatus = 'RUNNING' | 'SUCCESS' | 'FAILED';

export interface PipelineRun {
  id?: string;
  type: PipelineType;
  status: PipelineStatus;
  started_at: string;
  ended_at?: string;
  duration_seconds?: number;
  error_message?: string;
  metadata?: Record<string, any>;
}
