-- ============================================================================
-- AutoPilot AI Trading Bot - Complete Database Schema
-- Migration 003: Full AutoPilot Architecture
-- Date: 2025-12-26
-- Description: Replace signals-based schema with AutoPilot bot schema
-- ============================================================================

-- ============================================================================
-- STEP 1: DROP OLD TABLES (Signals-based SaaS)
-- ============================================================================

DROP TABLE IF EXISTS signal_explanations CASCADE;
DROP TABLE IF EXISTS signals CASCADE;
DROP TABLE IF EXISTS scanner_candidates CASCADE;
DROP TABLE IF EXISTS scanner_runs CASCADE;
DROP TABLE IF EXISTS watchlists CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS positions CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- Keep these if they exist
-- model_versions (keep for AI model tracking)
-- pipeline_runs (will modify)
-- audit_logs (will modify)

-- ============================================================================
-- STEP 2: CREATE CORE TABLES
-- ============================================================================

-- Profiles (User Settings & AutoPilot State)
CREATE TABLE profiles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    is_active_subscriber BOOLEAN DEFAULT false,
    autopilot_enabled BOOLEAN DEFAULT false,
    pro_mode BOOLEAN DEFAULT false, -- UI: dense panels
    cinematic_mode BOOLEAN DEFAULT true, -- UI: 3D + animations
    is_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Subscriptions (Razorpay)
CREATE TABLE subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
    razorpay_subscription_id TEXT UNIQUE NOT NULL,
    razorpay_customer_id TEXT NOT NULL,
    plan_period TEXT NOT NULL CHECK (plan_period IN ('monthly', 'yearly')),
    status TEXT NOT NULL CHECK (status IN ('active', 'cancelled', 'paused', 'expired')),
    current_period_start TIMESTAMPTZ NOT NULL,
    current_period_end TIMESTAMPTZ NOT NULL,
    cancel_at_period_end BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- BROKER INFRASTRUCTURE
-- ============================================================================

-- Broker Connections (Multi-Broker Support)
CREATE TABLE broker_connections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
    broker_type TEXT NOT NULL CHECK (broker_type IN (
        'zerodha', 'upstox', 'angel_one', 'dhan',
        'fyers', 'icici_breeze', 'kotak_neo', 'fivepaisa'
    )),
    encrypted_tokens TEXT NOT NULL, -- JSON encrypted: {api_key, access_token, etc.}
    status TEXT NOT NULL DEFAULT 'disconnected' CHECK (status IN ('connected', 'disconnected', 'error', 'refreshing')),
    last_refresh TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, broker_type) -- One connection per broker per user
);

-- Instruments (Canonical NSE/BSE Symbol Registry)
CREATE TABLE instruments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    canonical_symbol TEXT UNIQUE NOT NULL, -- e.g., "RELIANCE"
    exchange TEXT NOT NULL CHECK (exchange IN ('NSE', 'BSE')),
    name TEXT NOT NULL,
    isin TEXT,
    lot_size INTEGER DEFAULT 1,
    tick_size DECIMAL(10, 2) DEFAULT 0.05,
    sector TEXT,
    is_tradable BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Broker Instruments (Broker-Specific Token Mapping)
CREATE TABLE broker_instruments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    broker_type TEXT NOT NULL,
    canonical_symbol TEXT NOT NULL REFERENCES instruments(canonical_symbol) ON DELETE CASCADE,
    broker_token TEXT NOT NULL, -- Broker-specific instrument token
    broker_symbol TEXT NOT NULL, -- Broker-specific symbol format
    extra JSONB, -- Broker-specific metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(broker_type, canonical_symbol)
);

-- ============================================================================
-- TRADING SYSTEM (INTERNAL)
-- ============================================================================

-- Trade Intentions (INTERNAL - Generated by Daily Brain Pipeline)
-- NOT EXPOSED TO USERS
CREATE TABLE trade_intentions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL, -- Trade date
    canonical_symbol TEXT NOT NULL REFERENCES instruments(canonical_symbol),
    direction TEXT NOT NULL CHECK (direction IN ('BUY', 'SELL')),
    entry_zone_low DECIMAL(10, 2) NOT NULL,
    entry_zone_high DECIMAL(10, 2) NOT NULL,
    sl DECIMAL(10, 2) NOT NULL, -- Stop loss
    tp1 DECIMAL(10, 2) NOT NULL, -- Take profit 1
    tp2 DECIMAL(10, 2), -- Take profit 2 (optional)
    confidence DECIMAL(5, 4) NOT NULL CHECK (confidence >= 0 AND confidence <= 1), -- AI model score
    risk_grade TEXT NOT NULL CHECK (risk_grade IN ('LOW', 'MEDIUM', 'HIGH')),
    horizon TEXT NOT NULL CHECK (horizon IN ('INTRADAY', 'SWING', 'POSITIONAL')),
    tags JSONB DEFAULT '[]'::jsonb, -- High-level tags only: ["trend aligned", "volatility favorable"]
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ, -- Intention expires if not executed
    UNIQUE(date, canonical_symbol) -- One intention per symbol per day
);

-- Positions (User's Active Trades)
CREATE TABLE positions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
    canonical_symbol TEXT NOT NULL REFERENCES instruments(canonical_symbol),
    broker_type TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('LONG', 'SHORT')),
    quantity INTEGER NOT NULL,
    avg_entry_price DECIMAL(10, 2) NOT NULL,
    current_price DECIMAL(10, 2),
    unrealized_pnl DECIMAL(12, 2),
    unrealized_pnl_percent DECIMAL(8, 4),
    sl DECIMAL(10, 2) NOT NULL,
    tp1 DECIMAL(10, 2) NOT NULL,
    tp2 DECIMAL(10, 2),
    trailing_stop_enabled BOOLEAN DEFAULT false,
    trailing_stop_data JSONB, -- {initial_sl, current_sl, trail_points, highest_price}
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'PARTIALLY_CLOSED')),
    risk_snapshot JSONB NOT NULL, -- {risk_amount, risk_percent, position_size_method}
    trade_intention_id UUID REFERENCES trade_intentions(id),
    entry_timestamp TIMESTAMPTZ NOT NULL,
    exit_timestamp TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders (Execution Records)
CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
    broker_type TEXT NOT NULL,
    broker_order_id TEXT, -- Broker's order ID
    canonical_symbol TEXT NOT NULL REFERENCES instruments(canonical_symbol),
    side TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity INTEGER NOT NULL,
    order_type TEXT NOT NULL CHECK (order_type IN ('MARKET', 'LIMIT', 'SL', 'SL-M')),
    price DECIMAL(10, 2),
    trigger_price DECIMAL(10, 2),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN (
        'PENDING', 'OPEN', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED'
    )),
    filled_quantity INTEGER DEFAULT 0,
    average_fill_price DECIMAL(10, 2),
    slippage DECIMAL(10, 4), -- Difference between intended and actual price
    rejection_reason TEXT,
    position_id UUID REFERENCES positions(id),
    trade_intention_id UUID REFERENCES trade_intentions(id),
    is_paper_trade BOOLEAN DEFAULT true, -- Default to paper trading
    placed_at TIMESTAMPTZ,
    filled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Fills (Order Fill Details)
CREATE TABLE fills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    fill_price DECIMAL(10, 2) NOT NULL,
    fill_quantity INTEGER NOT NULL,
    fill_timestamp TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- RISK MANAGEMENT
-- ============================================================================

-- Risk Limits (Per User)
CREATE TABLE risk_limits (
    user_id UUID PRIMARY KEY REFERENCES profiles(user_id) ON DELETE CASCADE,
    max_positions INTEGER DEFAULT 5, -- Max open positions
    max_daily_loss DECIMAL(12, 2) DEFAULT 10000, -- Max loss per day (rupees)
    max_daily_loss_percent DECIMAL(5, 2) DEFAULT 2.0, -- Max loss per day (%)
    max_exposure DECIMAL(14, 2) DEFAULT 100000, -- Max total exposure (rupees)
    max_exposure_percent DECIMAL(5, 2) DEFAULT 80.0, -- Max % of capital deployed
    risk_per_trade_percent DECIMAL(5, 2) DEFAULT 1.0, -- Position sizing (% of capital)
    capital_allocated DECIMAL(14, 2) DEFAULT 100000, -- Total capital for AutoPilot
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- PERFORMANCE TRACKING
-- ============================================================================

-- Performance Daily (Aggregated Daily Stats)
CREATE TABLE performance_daily (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
    date DATE NOT NULL,
    trades_count INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0,
    win_rate DECIMAL(5, 4) DEFAULT 0, -- 0-1
    avg_r DECIMAL(8, 4) DEFAULT 0, -- Average R-multiple
    gross_pnl DECIMAL(12, 2) DEFAULT 0,
    net_pnl DECIMAL(12, 2) DEFAULT 0,
    fees DECIMAL(10, 2) DEFAULT 0,
    drawdown DECIMAL(12, 2) DEFAULT 0, -- Max intraday drawdown
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, date)
);

-- ============================================================================
-- NOTIFICATIONS & AUDIT
-- ============================================================================

-- Notifications (System Alerts)
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN (
        'ORDER_PLACED', 'ORDER_FILLED', 'ORDER_REJECTED',
        'POSITION_OPENED', 'POSITION_CLOSED',
        'RISK_LIMIT_BREACH', 'KILL_SWITCH_ACTIVATED',
        'BROKER_CONNECTION_ERROR', 'AUTOPILOT_PAUSED'
    )),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'INFO' CHECK (severity IN ('INFO', 'WARNING', 'ERROR')),
    read BOOLEAN DEFAULT false,
    action_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Audit Logs (Security & Compliance)
CREATE TABLE audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES profiles(user_id) ON DELETE SET NULL,
    action TEXT NOT NULL CHECK (action IN (
        'AUTOPILOT_ENABLED', 'AUTOPILOT_DISABLED',
        'ORDER_PLACED', 'ORDER_CANCELLED', 'POSITION_CLOSED',
        'RISK_LIMIT_UPDATED', 'KILL_SWITCH_ACTIVATED',
        'BROKER_CONNECTED', 'BROKER_DISCONNECTED'
    )),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pipeline Runs (Background Job Tracking)
CREATE TABLE pipeline_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT NOT NULL CHECK (type IN ('daily_brain', 'executor', 'position_monitor')),
    status TEXT NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    error_message TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Model Versions (AI Model Registry) - Keep from old schema
CREATE TABLE IF NOT EXISTS model_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    model_name TEXT NOT NULL,
    version TEXT NOT NULL,
    artifact_path TEXT NOT NULL, -- Supabase Storage path
    metrics JSONB, -- {accuracy, precision, recall, etc.}
    is_active BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(model_name, version)
);

-- ============================================================================
-- INDEXES (Performance Optimization)
-- ============================================================================

-- Profiles
CREATE INDEX idx_profiles_subscription ON profiles(is_active_subscriber);
CREATE INDEX idx_profiles_autopilot ON profiles(autopilot_enabled);

-- Subscriptions
CREATE INDEX idx_subscriptions_user ON subscriptions(user_id);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);
CREATE INDEX idx_subscriptions_period_end ON subscriptions(current_period_end);

-- Broker Connections
CREATE INDEX idx_broker_connections_user ON broker_connections(user_id);
CREATE INDEX idx_broker_connections_status ON broker_connections(status);

-- Trade Intentions
CREATE INDEX idx_trade_intentions_date ON trade_intentions(date);
CREATE INDEX idx_trade_intentions_symbol ON trade_intentions(canonical_symbol);
CREATE INDEX idx_trade_intentions_confidence ON trade_intentions(confidence DESC);

-- Positions
CREATE INDEX idx_positions_user ON positions(user_id);
CREATE INDEX idx_positions_status ON positions(status);
CREATE INDEX idx_positions_symbol ON positions(canonical_symbol);

-- Orders
CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_symbol ON orders(canonical_symbol);
CREATE INDEX idx_orders_created ON orders(created_at DESC);

-- Performance
CREATE INDEX idx_performance_user_date ON performance_daily(user_id, date DESC);

-- Notifications
CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_read ON notifications(read, created_at DESC);

-- Audit Logs
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at DESC);

-- Pipeline Runs
CREATE INDEX idx_pipeline_runs_type ON pipeline_runs(type);
CREATE INDEX idx_pipeline_runs_status ON pipeline_runs(status);
CREATE INDEX idx_pipeline_runs_started ON pipeline_runs(started_at DESC);

-- ============================================================================
-- TRIGGERS (Auto-update timestamps)
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON subscriptions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_broker_connections_updated_at BEFORE UPDATE ON broker_connections
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_instruments_updated_at BEFORE UPDATE ON instruments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_positions_updated_at BEFORE UPDATE ON positions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_risk_limits_updated_at BEFORE UPDATE ON risk_limits
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE profiles IS 'User profiles and AutoPilot settings';
COMMENT ON TABLE subscriptions IS 'Razorpay subscription data';
COMMENT ON TABLE broker_connections IS 'Multi-broker connections (Zerodha, Upstox, etc.)';
COMMENT ON TABLE instruments IS 'Canonical NSE/BSE symbol registry';
COMMENT ON TABLE broker_instruments IS 'Broker-specific instrument token mappings';
COMMENT ON TABLE trade_intentions IS 'INTERNAL: AI-generated trade intentions (NOT exposed to users)';
COMMENT ON TABLE positions IS 'Active user positions with trailing stops and risk data';
COMMENT ON TABLE orders IS 'Order execution history with slippage tracking';
COMMENT ON TABLE fills IS 'Detailed fill records for orders';
COMMENT ON TABLE risk_limits IS 'Per-user risk management limits';
COMMENT ON TABLE performance_daily IS 'Daily performance metrics for heatmap';
COMMENT ON TABLE notifications IS 'System notifications for users';
COMMENT ON TABLE audit_logs IS 'Security and compliance audit trail';
COMMENT ON TABLE pipeline_runs IS 'Background pipeline execution logs';
COMMENT ON TABLE model_versions IS 'AI model artifact registry';
